/* Example words per sound — [kana, romaji, meaning]. Two common, kana-spelled
   words each; rare word-initial sounds (ru, n) use words that contain them.
   wo is only ever the object particle, so it has no word list. */
const WORDS = {
  a:  [["あさ","asa","morning"],["あめ","ame","rain"]],
  i:  [["いぬ","inu","dog"],["いえ","ie","house"]],
  u:  [["うみ","umi","sea"],["うた","uta","song"]],
  e:  [["えき","eki","station"],["えいが","eiga","film"]],
  o:  [["おちゃ","ocha","tea"],["おかね","okane","money"]],
  ka: [["かさ","kasa","umbrella"],["かわ","kawa","river"]],
  ki: [["きって","kitte","stamp"],["きた","kita","north"]],
  ku: [["くつ","kutsu","shoes"],["くも","kumo","cloud"]],
  ke: [["けさ","kesa","this morning"],["けが","kega","injury"]],
  ko: [["こども","kodomo","child"],["ここ","koko","here"]],
  sa: [["さかな","sakana","fish"],["さくら","sakura","cherry blossom"]],
  shi:[["しお","shio","salt"],["しま","shima","island"]],
  su: [["すし","sushi","sushi"],["すな","suna","sand"]],
  se: [["せなか","senaka","back (body)"],["せき","seki","seat"]],
  so: [["そら","sora","sky"],["そと","soto","outside"]],
  ta: [["たまご","tamago","egg"],["たけ","take","bamboo"]],
  chi:[["ちず","chizu","map"],["ちから","chikara","strength"]],
  tsu:[["つき","tsuki","moon"],["つくえ","tsukue","desk"]],
  te: [["てがみ","tegami","letter"],["てら","tera","temple"]],
  to: [["とり","tori","bird"],["とけい","tokei","clock"]],
  na: [["なつ","natsu","summer"],["なまえ","namae","name"]],
  ni: [["にく","niku","meat"],["にわ","niwa","garden"]],
  nu: [["ぬの","nuno","cloth"],["ぬま","numa","marsh"]],
  ne: [["ねこ","neko","cat"],["ねつ","netsu","fever"]],
  no: [["のり","nori","seaweed"],["のみもの","nomimono","drink"]],
  ha: [["はな","hana","flower"],["はし","hashi","chopsticks"]],
  hi: [["ひと","hito","person"],["ひる","hiru","noon"]],
  fu: [["ふゆ","fuyu","winter"],["ふね","fune","boat"]],
  he: [["へや","heya","room"],["へび","hebi","snake"]],
  ho: [["ほし","hoshi","star"],["ほん","hon","book"]],
  ma: [["まど","mado","window"],["まち","machi","town"]],
  mi: [["みず","mizu","water"],["みみ","mimi","ear"]],
  mu: [["むし","mushi","insect"],["むら","mura","village"]],
  me: [["めがね","megane","glasses"],["めん","men","noodles"]],
  mo: [["もり","mori","forest"],["もも","momo","peach"]],
  ya: [["やま","yama","mountain"],["やさい","yasai","vegetable"]],
  yu: [["ゆき","yuki","snow"],["ゆび","yubi","finger"]],
  yo: [["よる","yoru","night"],["よこ","yoko","side"]],
  ra: [["らいねん","rainen","next year"],["らく","raku","easy, comfortable"]],
  ri: [["りんご","ringo","apple"],["りす","risu","squirrel"]],
  ru: [["るす","rusu","away from home"],["はる","haru","spring — る mid-word"]],
  re: [["れきし","rekishi","history"],["れい","rei","zero"]],
  ro: [["ろく","roku","six"],["いろ","iro","colour — ろ at the end"]],
  wa: [["わたし","watashi","I, me"],["わに","wani","crocodile"]],
  n:  [["みかん","mikan","mandarin"],["うどん","udon","udon noodles"]],
};
