const DATA = [
["Greetings","あいさつ",[
 [["お","は","よ","う","ご","ざ","い","ま","す"],["o","ha","yo","u","go","za","i","ma","su"],"Good morning — polite"],
 [["お","は","よ","う"],["o","ha","yo","u"],"Morning — casual"],
 [["こ","ん","に","ち","は"],["ko","n","ni","chi","*wa"],"Hello / good afternoon"],
 [["こ","ん","ば","ん","は"],["ko","n","ba","n","*wa"],"Good evening"],
 [["お","や","す","み","な","さ","い"],["o","ya","su","mi","na","sa","i"],"Good night"],
 [["さ","よ","う","な","ら"],["sa","yo","u","na","ra"],"Goodbye — a long parting"],
 [["ま","た","ね"],["ma","ta","ne"],"See you — casual"],
 [["ま","た","あ","し","た"],["ma","ta","a","shi","ta"],"See you tomorrow"],
 [["は","じ","め","ま","し","て"],["ha","ji","me","ma","shi","te"],"Nice to meet you"],
 [["よ","ろ","し","く","お","ね","が","い","し","ま","す"],["yo","ro","shi","ku","o","ne","ga","i","shi","ma","su"],"Looking forward to it — said on meeting, joining, or asking a favour"],
 [["お","げ","ん","き","で","す","か"],["o","ge","n","ki","de","su","ka"],"How are you?"],
 [["お","ひ","さ","し","ぶ","り","で","す"],["o","hi","sa","shi","bu","ri","de","su"],"Long time no see"],
 [["い","っ","て","き","ま","す"],["i","~","te","ki","ma","su"],"I'm off — said as you leave home"],
 [["い","っ","て","ら","っ","しゃ","い"],["i","~","te","ra","~","sha","i"],"Have a good one — said to the person leaving"],
 [["た","だ","い","ま"],["ta","da","i","ma"],"I'm home"],
 [["お","か","え","り","な","さ","い"],["o","ka","e","ri","na","sa","i"],"Welcome back"]
]],
["Please and thank you","れいぎ",[
 [["あ","り","が","と","う","ご","ざ","い","ま","す"],["a","ri","ga","to","u","go","za","i","ma","su"],"Thank you — polite"],
 [["あ","り","が","と","う"],["a","ri","ga","to","u"],"Thanks — casual"],
 [["ど","う","い","た","し","ま","し","て"],["do","u","i","ta","shi","ma","shi","te"],"You're welcome"],
 [["す","み","ま","せ","ん"],["su","mi","ma","se","n"],"Excuse me / sorry — also how you flag down staff"],
 [["ご","め","ん","な","さ","い"],["go","me","n","na","sa","i"],"I'm sorry"],
 [["お","ね","が","い","し","ま","す"],["o","ne","ga","i","shi","ma","su"],"Please — attach it to any request"],
 [["ど","う","ぞ"],["do","u","zo"],"Go ahead / here you go"],
 [["だ","い","じょ","う","ぶ","で","す"],["da","i","jo","u","bu","de","su"],"It's fine / I'm okay"],
 [["け","っ","こ","う","で","す"],["ke","~","ko","u","de","su"],"No thank you"],
 [["し","つ","れ","い","し","ま","す"],["shi","tsu","re","i","shi","ma","su"],"Excuse me — entering or leaving a room"],
 [["お","つ","か","れ","さ","ま","で","す"],["o","tsu","ka","re","sa","ma","de","su"],"Thanks for your work — the all-purpose office greeting"]
]],
["Yes, no, say that again","へんじ",[
 [["は","い"],["ha","i"],"Yes"],
 [["い","い","え"],["i","i","e"],"No"],
 [["わ","か","り","ま","し","た"],["wa","ka","ri","ma","shi","ta"],"Understood / got it"],
 [["わ","か","り","ま","せ","ん"],["wa","ka","ri","ma","se","n"],"I don't understand"],
 [["し","り","ま","せ","ん"],["shi","ri","ma","se","n"],"I don't know"],
 [["に","ほ","ん","ご","が","す","こ","し","わ","か","り","ま","す"],["ni","ho","n","go","ga","su","ko","shi","wa","ka","ri","ma","su"],"I understand a little Japanese"],
 [["え","い","ご","を","は","な","せ","ま","す","か"],["e","i","go","*o","ha","na","se","ma","su","ka"],"Do you speak English?"],
 [["も","う","い","ち","ど","お","ね","が","い","し","ま","す"],["mo","u","i","chi","do","o","ne","ga","i","shi","ma","su"],"One more time, please"],
 [["ゆ","っ","く","り","お","ね","が","い","し","ま","す"],["yu","~","ku","ri","o","ne","ga","i","shi","ma","su"],"Slowly, please"],
 [["こ","れ","で","い","い","で","す","か"],["ko","re","de","i","i","de","su","ka"],"Is this okay?"],
 [["な","ん","と","い","い","ま","す","か"],["na","n","to","i","i","ma","su","ka"],"How do you say it?"]
]],
["Introducing yourself","じこしょうかい",[
 [["わ","た","し","は","ク","イ","ン","シ","ー","で","す"],["wa","ta","shi","*wa","ku","i","n","shi","~","de","su"],"I'm Quincy — your name in katakana"],
 [["カ","ナ","ダ","か","ら","き","ま","し","た"],["ka","na","da","ka","ra","ki","ma","shi","ta"],"I'm from Canada"],
 [["エ","ン","ジ","ニ","ア","で","す"],["e","n","ji","ni","a","de","su"],"I'm an engineer"],
 [["に","ほ","ん","ご","を","べ","ん","きょ","う","し","て","い","ま","す"],["ni","ho","n","go","*o","be","n","kyo","u","shi","te","i","ma","su"],"I'm studying Japanese"],
 [["お","な","ま","え","は","な","ん","で","す","か"],["o","na","ma","e","*wa","na","n","de","su","ka"],"What's your name?"],
 [["し","ご","と","は","な","ん","で","す","か"],["shi","go","to","*wa","na","n","de","su","ka"],"What do you do for work?"],
 [["と","う","きょ","う","に","す","ん","で","い","ま","す"],["to","u","kyo","u","ni","su","n","de","i","ma","su"],"I live in Tokyo"],
 [["しゅ","み","は","な","ん","で","す","か"],["shu","mi","*wa","na","n","de","su","ka"],"What do you do for fun?"]
]],
["Shops and food","かいもの",[
 [["こ","れ","を","く","だ","さ","い"],["ko","re","*o","ku","da","sa","i"],"This one, please — point and say it"],
 [["い","く","ら","で","す","か"],["i","ku","ra","de","su","ka"],"How much is it?"],
 [["メ","ニュ","ー","を","お","ね","が","い","し","ま","す"],["me","nyu","~","*o","o","ne","ga","i","shi","ma","su"],"Menu, please"],
 [["お","す","す","め","は","な","ん","で","す","か"],["o","su","su","me","*wa","na","n","de","su","ka"],"What do you recommend?"],
 [["ひ","と","り","で","す"],["hi","to","ri","de","su"],"Just one — table for one"],
 [["い","た","だ","き","ま","す"],["i","ta","da","ki","ma","su"],"Said just before you eat"],
 [["お","い","し","い","で","す"],["o","i","shi","i","de","su"],"It's delicious"],
 [["ご","ち","そ","う","さ","ま","で","し","た"],["go","chi","so","u","sa","ma","de","shi","ta"],"Said when you finish eating"],
 [["み","ず","を","く","だ","さ","い"],["mi","zu","*o","ku","da","sa","i"],"Water, please"],
 [["に","く","は","た","べ","ま","せ","ん"],["ni","ku","*wa","ta","be","ma","se","n"],"I don't eat meat"],
 [["も","ち","か","え","り","で","す"],["mo","chi","ka","e","ri","de","su"],"Takeaway"],
 [["て","ん","な","い","で","た","べ","ま","す"],["te","n","na","i","de","ta","be","ma","su"],"Eating in"],
 [["お","か","い","け","い","お","ね","が","い","し","ま","す"],["o","ka","i","ke","i","o","ne","ga","i","shi","ma","su"],"The bill, please"],
 [["カ","ー","ド","で","い","い","で","す","か"],["ka","~","do","de","i","i","de","su","ka"],"Is card okay?"],
 [["ふ","く","ろ","は","い","り","ま","せ","ん"],["fu","ku","ro","*wa","i","ri","ma","se","n"],"I don't need a bag"],
 [["す","こ","し","ま","っ","て","く","だ","さ","い"],["su","ko","shi","ma","~","te","ku","da","sa","i"],"One moment, please"],
 [["み","て","い","る","だ","け","で","す"],["mi","te","i","ru","da","ke","de","su"],"Just looking, thanks"]
]],
["Getting around","みち・でんしゃ",[
 [["ト","イ","レ","は","ど","こ","で","す","か"],["to","i","re","*wa","do","ko","de","su","ka"],"Where is the toilet?"],
 [["え","き","は","ど","こ","で","す","か"],["e","ki","*wa","do","ko","de","su","ka"],"Where is the station?"],
 [["こ","こ","は","ど","こ","で","す","か"],["ko","ko","*wa","do","ko","de","su","ka"],"Where am I?"],
 [["こ","れ","は","な","ん","で","す","か"],["ko","re","*wa","na","n","de","su","ka"],"What is this?"],
 [["み","ぎ"],["mi","gi"],"Right"],
 [["ひ","だ","り"],["hi","da","ri"],"Left"],
 [["ま","っ","す","ぐ"],["ma","~","su","gu"],"Straight ahead"],
 [["ち","か","い","で","す","か"],["chi","ka","i","de","su","ka"],"Is it close?"],
 [["あ","る","い","て","い","け","ま","す","か"],["a","ru","i","te","i","ke","ma","su","ka"],"Can I walk there?"],
 [["み","ち","に","ま","よ","い","ま","し","た"],["mi","chi","ni","ma","yo","i","ma","shi","ta"],"I'm lost"],
 [["な","ん","ば","ん","せ","ん","で","す","か"],["na","n","ba","n","se","n","de","su","ka"],"Which platform?"],
 [["つ","ぎ","の","で","ん","しゃ","は","な","ん","じ","で","す","か"],["tsu","gi","no","de","n","sha","*wa","na","n","ji","de","su","ka"],"What time is the next train?"],
 [["き","っ","ぷ","を","か","い","た","い","で","す"],["ki","~","pu","*o","ka","i","ta","i","de","su"],"I'd like to buy a ticket"],
 [["と","う","きょ","う","ま","で","お","ね","が","い","し","ま","す"],["to","u","kyo","u","ma","de","o","ne","ga","i","shi","ma","su"],"To Tokyo, please — say it to a taxi driver"]
]],
["Numbers and time","かず・じかん",[
 [["い","ち"],["i","chi"],"1"],
 [["に"],["ni"],"2"],
 [["さ","ん"],["sa","n"],"3"],
 [["よ","ん"],["yo","n"],"4"],
 [["ご"],["go"],"5"],
 [["ろ","く"],["ro","ku"],"6"],
 [["な","な"],["na","na"],"7"],
 [["は","ち"],["ha","chi"],"8"],
 [["きゅ","う"],["kyu","u"],"9"],
 [["じゅ","う"],["ju","u"],"10"],
 [["ひゃ","く"],["hya","ku"],"100"],
 [["せ","ん"],["se","n"],"1,000"],
 [["ま","ん"],["ma","n"],"10,000 — Japanese counts in units of man, so ¥30,000 is san-man"],
 [["い","ま","な","ん","じ","で","す","か"],["i","ma","na","n","ji","de","su","ka"],"What time is it?"],
 [["きょ","う"],["kyo","u"],"Today"],
 [["あ","し","た"],["a","shi","ta"],"Tomorrow"],
 [["き","の","う"],["ki","no","u"],"Yesterday"]
]],
["Renting and daily life","せいかつ",[
 [["よ","や","く","を","し","た","い","で","す"],["yo","ya","ku","*o","shi","ta","i","de","su"],"I'd like to make a booking"],
 [["イ","ン","タ","ー","ネ","ッ","ト","は","あ","り","ま","す","か"],["i","n","ta","~","ne","~","to","*wa","a","ri","ma","su","ka"],"Is there internet?"],
 [["げ","ん","き","ん","だ","け","で","す","か"],["ge","n","ki","n","da","ke","de","su","ka"],"Cash only?"],
 [["は","ん","こ","が","ひ","つ","よ","う","で","す","か"],["ha","n","ko","ga","hi","tsu","yo","u","de","su","ka"],"Do I need a personal seal?"],
 [["な","ま","え","を","か","い","て","く","だ","さ","い"],["na","ma","e","*o","ka","i","te","ku","da","sa","i"],"Please write your name"],
 [["ご","み","の","ひ","は","い","つ","で","す","か"],["go","mi","no","hi","*wa","i","tsu","de","su","ka"],"Which day is rubbish day? — Japan takes this seriously"],
 [["こ","わ","れ","て","い","ま","す"],["ko","wa","re","te","i","ma","su"],"It's broken"],
 [["しゅ","う","り","を","お","ね","が","い","し","ま","す"],["shu","u","ri","*o","o","ne","ga","i","shi","ma","su"],"Please arrange a repair"],
 [["ペ","ッ","ト","を","か","っ","て","い","ま","す"],["pe","~","to","*o","ka","~","te","i","ma","su"],"I have pets"],
 [["で","ん","き","を","つ","け","て","く","だ","さ","い"],["de","n","ki","*o","tsu","ke","te","ku","da","sa","i"],"Please turn on the light"]
]],
["If something goes wrong","きんきゅう",[
 [["た","す","け","て"],["ta","su","ke","te"],"Help!"],
 [["びょ","う","い","ん","は","ど","こ","で","す","か"],["byo","u","i","n","*wa","do","ko","de","su","ka"],"Where is the hospital?"],
 [["け","い","さ","つ","を","よ","ん","で","く","だ","さ","い"],["ke","i","sa","tsu","*o","yo","n","de","ku","da","sa","i"],"Please call the police"],
 [["きゅ","う","きゅ","う","しゃ","を","よ","ん","で","く","だ","さ","い"],["kyu","u","kyu","u","sha","*o","yo","n","de","ku","da","sa","i"],"Please call an ambulance"],
 [["さ","い","ふ","を","な","く","し","ま","し","た"],["sa","i","fu","*o","na","ku","shi","ma","shi","ta"],"I lost my wallet"],
 [["パ","ス","ポ","ー","ト","を","な","く","し","ま","し","た"],["pa","su","po","~","to","*o","na","ku","shi","ma","shi","ta"],"I lost my passport"],
 [["き","ぶ","ん","が","わ","る","い","で","す"],["ki","bu","n","ga","wa","ru","i","de","su"],"I don't feel well"],
 [["ア","レ","ル","ギ","ー","が","あ","り","ま","す"],["a","re","ru","gi","~","ga","a","ri","ma","su"],"I have an allergy"],
 [["で","ん","わ","を","か","し","て","く","だ","さ","い"],["de","n","wa","*o","ka","shi","te","ku","da","sa","i"],"Please lend me a phone"]
]],
["Reacting like a human","きもち",[
 [["す","ご","い"],["su","go","i"],"Wow / amazing"],
 [["か","わ","い","い"],["ka","wa","i","i"],"Cute"],
 [["た","の","し","い","で","す"],["ta","no","shi","i","de","su"],"This is fun"],
 [["う","れ","し","い","で","す"],["u","re","shi","i","de","su"],"I'm happy"],
 [["つ","か","れ","ま","し","た"],["tsu","ka","re","ma","shi","ta"],"I'm worn out"],
 [["あ","つ","い","で","す","ね"],["a","tsu","i","de","su","ne"],"Hot today, isn't it — the national small talk"],
 [["さ","む","い","で","す","ね"],["sa","mu","i","de","su","ne"],"Cold, isn't it"],
 [["ほ","ん","と","う","で","す","か"],["ho","n","to","u","de","su","ka"],"Really?"],
 [["な","る","ほ","ど"],["na","ru","ho","do"],"Ah, I see — that makes sense"],
 [["だ","い","す","き","で","す"],["da","i","su","ki","de","su"],"I love it"]
]],
["Katakana you already know","カタカナ",[
 [["コ","ー","ヒ","ー"],["ko","~","hi","~"],"coffee — kōhī"],
 [["ビ","ー","ル"],["bi","~","ru"],"beer — bīru"],
 [["ト","イ","レ"],["to","i","re"],"toilet"],
 [["コ","ン","ビ","ニ"],["ko","n","bi","ni"],"convenience store"],
 [["ス","ー","パ","ー"],["su","~","pa","~"],"supermarket"],
 [["レ","ス","ト","ラ","ン"],["re","su","to","ra","n"],"restaurant"],
 [["ホ","テ","ル"],["ho","te","ru"],"hotel"],
 [["タ","ク","シ","ー"],["ta","ku","shi","~"],"taxi"],
 [["バ","ス"],["ba","su"],"bus"],
 [["エ","レ","ベ","ー","タ","ー"],["e","re","be","~","ta","~"],"elevator"],
 [["カ","ー","ド"],["ka","~","do"],"card"],
 [["パ","ス","ポ","ー","ト"],["pa","su","po","~","to"],"passport"],
 [["チェ","ッ","ク","イ","ン"],["che","~","ku","i","n"],"check-in"],
 [["イ","ン","タ","ー","ネ","ッ","ト"],["i","n","ta","~","ne","~","to"],"internet"],
 [["ワ","イ","ファ","イ"],["wa","i","fa","i"],"Wi-Fi"],
 [["パ","ソ","コ","ン"],["pa","so","ko","n"],"computer — from \u201cpersonal computer\u201d"],
 [["ス","マ","ホ"],["su","ma","ho"],"smartphone — clipped from sumātofon"],
 [["サ","ー","バ","ー"],["sa","~","ba","~"],"server"],
 [["ア","プ","リ"],["a","pu","ri"],"app"],
 [["メ","ー","ル"],["me","~","ru"],"email"],
 [["エ","ン","ジ","ニ","ア"],["e","n","ji","ni","a"],"engineer"],
 [["カ","ナ","ダ","じ","ん"],["ka","na","da","ji","n"],"Canadian — kanji-era word plus katakana country"]
]]
];

/* kanji signs: [kanji, furigana, romaji, meaning, where you'll see it] */
const KANJI=[
 ["出口","でぐち","deguchi","exit","every station and shop"],
 ["入口","いりぐち","iriguchi","entrance","doors, gates"],
 ["駅","えき","eki","station","maps, signs"],
 ["円","えん","en","yen","every price tag"],
 ["改札","かいさつ","kaisatsu","ticket gate","stations"],
 ["電車","でんしゃ","densha","train","platforms, apps"],
 ["銀行","ぎんこう","ginkō","bank","street signs"],
 ["病院","びょういん","byōin","hospital","maps, buildings"],
 ["薬局","やっきょく","yakkyoku","pharmacy","green cross signs"],
 ["押","おす","osu","push","door handles"],
 ["引","ひく","hiku","pull","door handles"],
 ["開","ひらく","hiraku","open","elevator buttons"],
 ["閉","しめる","shimeru","close","elevator buttons"],
 ["営業中","えいぎょうちゅう","eigyōchū","open for business","shop doors"],
 ["準備中","じゅんびちゅう","junbichū","closed — preparing","shop doors"],
 ["男","おとこ","otoko","men","toilets, baths"],
 ["女","おんな","onna","women","toilets, baths"],
 ["水","みず","mizu","water","taps, menus"],
 ["お湯","おゆ","oyu","hot water","taps, baths"],
 ["大","だい","dai","large","sizes, flush buttons"],
 ["小","しょう","shō","small","sizes, flush buttons"],
 ["無料","むりょう","muryō","free of charge","signs, apps"],
 ["有料","ゆうりょう","yūryō","paid / fee applies","parking, toilets"],
 ["割引","わりびき","waribiki","discount","supermarket stickers"],
 ["税込","ぜいこみ","zeikomi","tax included","price tags"],
 ["受付","うけつけ","uketsuke","reception","offices, clinics"],
 ["非常口","ひじょうぐち","hijōguchi","emergency exit","green running-man sign"],
 ["注意","ちゅうい","chūi","caution","yellow signs"],
 ["危険","きけん","kiken","danger","red signs"],
 ["止まれ","とまれ","tomare","stop","road markings"]
];

const GOJU=[
 ["—",[["あ","ア","a"],["い","イ","i"],["う","ウ","u"],["え","エ","e"],["お","オ","o"]]],
 ["K",[["か","カ","ka"],["き","キ","ki"],["く","ク","ku"],["け","ケ","ke"],["こ","コ","ko"]]],
 ["S",[["さ","サ","sa"],["し","シ","shi",1],["す","ス","su"],["せ","セ","se"],["そ","ソ","so"]]],
 ["T",[["た","タ","ta"],["ち","チ","chi",1],["つ","ツ","tsu",1],["て","テ","te"],["と","ト","to"]]],
 ["N",[["な","ナ","na"],["に","ニ","ni"],["ぬ","ヌ","nu"],["ね","ネ","ne"],["の","ノ","no"]]],
 ["H",[["は","ハ","ha"],["ひ","ヒ","hi"],["ふ","フ","fu",1],["へ","ヘ","he"],["ほ","ホ","ho"]]],
 ["M",[["ま","マ","ma"],["み","ミ","mi"],["む","ム","mu"],["め","メ","me"],["も","モ","mo"]]],
 ["Y",[["や","ヤ","ya"],null,["ゆ","ユ","yu"],null,["よ","ヨ","yo"]]],
 ["R",[["ら","ラ","ra"],["り","リ","ri"],["る","ル","ru"],["れ","レ","re"],["ろ","ロ","ro"]]],
 ["W",[["わ","ワ","wa"],null,null,null,["を","ヲ","o",1]]],
 ["N",[["ん","ン","n"],null,null,null,null]]
];
const DAKU=[
 ["G",[["が","ガ","ga"],["ぎ","ギ","gi"],["ぐ","グ","gu"],["げ","ゲ","ge"],["ご","ゴ","go"]]],
 ["Z",[["ざ","ザ","za"],["じ","ジ","ji",1],["ず","ズ","zu"],["ぜ","ゼ","ze"],["ぞ","ゾ","zo"]]],
 ["D",[["だ","ダ","da"],["ぢ","ヂ","ji",1],["づ","ヅ","zu",1],["で","デ","de"],["ど","ド","do"]]],
 ["B",[["ば","バ","ba"],["び","ビ","bi"],["ぶ","ブ","bu"],["べ","ベ","be"],["ぼ","ボ","bo"]]],
 ["P",[["ぱ","パ","pa"],["ぴ","ピ","pi"],["ぷ","プ","pu"],["ぺ","ペ","pe"],["ぽ","ポ","po"]]]
];
const YOON=[
 ["K",[["きゃ","キャ","kya"],["きゅ","キュ","kyu"],["きょ","キョ","kyo"]]],
 ["S",[["しゃ","シャ","sha",1],["しゅ","シュ","shu",1],["しょ","ショ","sho",1]]],
 ["T",[["ちゃ","チャ","cha",1],["ちゅ","チュ","chu",1],["ちょ","チョ","cho",1]]],
 ["N",[["にゃ","ニャ","nya"],["にゅ","ニュ","nyu"],["にょ","ニョ","nyo"]]],
 ["H",[["ひゃ","ヒャ","hya"],["ひゅ","ヒュ","hyu"],["ひょ","ヒョ","hyo"]]],
 ["M",[["みゃ","ミャ","mya"],["みゅ","ミュ","myu"],["みょ","ミョ","myo"]]],
 ["R",[["りゃ","リャ","rya"],["りゅ","リュ","ryu"],["りょ","リョ","ryo"]]],
 ["G",[["ぎゃ","ギャ","gya"],["ぎゅ","ギュ","gyu"],["ぎょ","ギョ","gyo"]]],
 ["J",[["じゃ","ジャ","ja",1],["じゅ","ジュ","ju",1],["じょ","ジョ","jo",1]]],
 ["B",[["びゃ","ビャ","bya"],["びゅ","ビュ","byu"],["びょ","ビョ","byo"]]],
 ["P",[["ぴゃ","ピャ","pya"],["ぴゅ","ピュ","pyu"],["ぴょ","ピョ","pyo"]]]
];
const EXTRA=[["ファ","fa"],["フィ","fi"],["フェ","fe"],["フォ","fo"],["ティ","ti"],["ディ","di"],["トゥ","tu"],["ドゥ","du"],["ウィ","wi"],["ウェ","we"],["ウォ","wo"],["チェ","che"],["シェ","she"],["ジェ","je"],["ヴ","vu"],["クォ","kwo"]];


/* Mnemonics for the 46 base characters (from the guide) — [hiragana, katakana] keyed by romaji. */
const MNEM = {"a":["An <b>apple</b>: a cross for the stem, a loop for the fruit.","An <b>axe</b> head with the handle slanting off."],"i":["Two <b>icicles</b> hanging off a gutter, one longer.","An <b>easel</b> leg propping up a canvas."],"u":["A <b>duck</b> in profile, beak tipped up going \"oo\".","A <b>roof</b> with a chimney — you're under it going \"ooh\"."],"e":["A <b>swan</b>: long neck, flat back on the water.","An <b>I-beam</b> girder — an engineer's E."],"o":["A <b>golf</b> ball flying off the tee, flag flicking right.","An <b>oar</b> dipping into the water."],"ka":["A <b>kite</b> with the string whipping off it.","A <b>karate</b> chop splitting a board."],"ki":["A <b>key</b> with two teeth.","The same <b>key</b>, teeth filed flat."],"ku":["A <b>cuckoo's</b> open beak.","A <b>croissant</b> curl."],"ke":["A <b>keg</b> with the tap on its side.","A <b>kettle</b> with a handle."],"ko":["Two <b>coins</b> stacked flat.","A <b>corner</b> bracket — half a box."],"sa":["A <b>sardine</b> on a hook, crossed by the rod.","A <b>cactus</b> with two arms, stuck in <b>sand</b>."],"shi":["A <b>shoehorn</b> curving up at the heel.","A <b>smiley</b> tipped left — two eyes and a wink."],"su":["A <b>swing</b> hanging from a looped rope.","A <b>ski</b> slope with a jump at the bottom."],"se":["A <b>seesaw</b> on its post, tipping back.","A <b>scythe</b> curving to its point."],"so":["A zigzag <b>stitch</b> — sewing.","Two loose <b>stitches</b> of the same thread."],"ta":["Literally a <b>t</b> next to an <b>a</b>: ta.","A luggage <b>tag</b> with a slash across it."],"chi":["A <b>cheerleader</b> leaning back, ponytail out.","A <b>cheap</b> price tag — a 7 with a line through it."],"tsu":["A <b>tsunami</b> curling over.","The same wave with three <b>droplets</b> flying off."],"te":["A <b>telephone</b> pole with the wire drooping.","A <b>TV antenna</b> on a roof."],"to":["A <b>toe</b> with a splinter in it.","A <b>totem</b> pole with one peg."],"na":["A <b>knot</b> tied in a rope.","A <b>knife</b> driven through a board."],"ni":["A <b>needle</b> and two stitches beside it.","Two lines — and <b>ni</b> means <b>two</b> in Japanese."],"nu":["<b>Noodles</b> twirled on chopsticks, one strand escaping.","The same <b>noodles</b>, chopsticks crossed, no loop."],"ne":["A <b>cat</b> curled up with its tail looping (猫 = neko).","A <b>nest</b> wedged in a tree fork."],"no":["The swirl of a <b>\"no entry\"</b> sign.","A single slash: <b>no</b>."],"ha":["A capital <b>H</b> with a small a — and a <b>house</b> with a chimney.","Two legs of someone doubled over laughing, <b>ha ha</b>."],"hi":["A wide <b>grin</b> — hee hee.","The <b>heel</b> of a shoe from the side."],"fu":["Mount <b>Fuji</b> with two clouds beside it.","The bare slope of <b>Fuji</b> in one stroke."],"he":["A <b>hill</b> you hike over. Same shape in both scripts.","The same <b>hill</b> — the one freebie in the whole chart."],"ho":["The は <b>house</b> plus an antenna — Santa on the roof, ho ho ho.","A <b>totem</b> pole with two arms."],"ma":["<b>Mama</b> with two arms out and a bun in her hair.","An open <b>mouth</b> with the tongue showing."],"mi":["A <b>mermaid's</b> tail curling under her.","Three strokes — and <b>mi</b> means <b>three</b> in Japanese."],"mu":["A <b>cow</b> face: muuu.","A <b>muzzle</b>, or a scoop tipped forward."],"me":["An <b>eye</b> with a lash — め literally means eye.","<b>X marks the spot</b> on a treasure map."],"mo":["A fishing hook with two <b>more</b> worms on it.","The same hook, straightened out."],"ya":["A <b>yacht</b> with mast and sail.","The same <b>yacht</b>, sail only."],"yu":["A <b>yo-yo</b> at the end of its string.","A <b>U-magnet</b> lying on its side."],"yo":["Someone doing <b>yoga</b>, folded over their knees.","A <b>comb</b> with three teeth."],"ra":["A <b>rabbit</b> sitting up, one ear laid back.","A bowl of <b>ramen</b> on a table."],"ri":["Two banks of a <b>river</b>.","The same <b>river</b>, straightened."],"ru":["A <b>route</b> that loops back on itself.","Two legs <b>running</b> that route."],"re":["A <b>ribbon</b> streaming off to the side.","A <b>ramp</b> — or a hockey stick."],"ro":["A <b>road</b> with no loop — dead end.","A <b>robot's</b> square head."],"wa":["A <b>whale</b> with a curl of spout.","An open mouth: <b>wah!</b>"],"wo":["An <b>ox</b> with horns, dragging a yoke behind it.","Essentially never used — recognise it, don't drill it."],"n":["A lazy cursive <b>n</b>.","A <b>wink</b> — one eye, one lash sweeping up."]};
