const DATA = [
["Greetings","あいさつ",[
 [["お","は","よ","う","ご","ざ","い","ま","す"],["o","ha","yo","u","go","za","i","ma","su"],"Good morning — polite"],
 [["お","は","よ","う"],["o","ha","yo","u"],"Morning — casual"],
 [["こ","ん","に","ち","は"],["ko","n","ni","chi","*wa"],"Hello / good afternoon"],
 [["こ","ん","ば","ん","は"],["ko","n","ba","n","*wa"],"Good evening"],
 [["お","や","す","み","な","さ","い"],["o","ya","su","mi","na","sa","i"],"Good night"],
 [["さ","よ","う","な","ら"],["sa","yo","u","na","ra"],"Goodbye — a long parting"],
 [["ま","た","ね"],["ma","ta","ne"],"See you — casual"],
 [["ま","た","あ","し","た"],["ma","ta","a","shi","ta"],"See you tomorrow"],
 [["は","じ","め","ま","し","て"],["ha","ji","me","ma","shi","te"],"Nice to meet you"],
 [["よ","ろ","し","く","お","ね","が","い","し","ま","す"],["yo","ro","shi","ku","o","ne","ga","i","shi","ma","su"],"Looking forward to it — said on meeting, joining, or asking a favour"],
 [["お","げ","ん","き","で","す","か"],["o","ge","n","ki","de","su","ka"],"How are you?"],
 [["お","ひ","さ","し","ぶ","り","で","す"],["o","hi","sa","shi","bu","ri","de","su"],"Long time no see"],
 [["い","っ","て","き","ま","す"],["i","~","te","ki","ma","su"],"I'm off — said as you leave home"],
 [["い","っ","て","ら","っ","しゃ","い"],["i","~","te","ra","~","sha","i"],"Have a good one — said to the person leaving"],
 [["た","だ","い","ま"],["ta","da","i","ma"],"I'm home"],
 [["お","か","え","り","な","さ","い"],["o","ka","e","ri","na","sa","i"],"Welcome back"]
]],
["Please and thank you","れいぎ",[
 [["あ","り","が","と","う","ご","ざ","い","ま","す"],["a","ri","ga","to","u","go","za","i","ma","su"],"Thank you — polite"],
 [["あ","り","が","と","う"],["a","ri","ga","to","u"],"Thanks — casual"],
 [["ど","う","い","た","し","ま","し","て"],["do","u","i","ta","shi","ma","shi","te"],"You're welcome"],
 [["す","み","ま","せ","ん"],["su","mi","ma","se","n"],"Excuse me / sorry — also how you flag down staff"],
 [["ご","め","ん","な","さ","い"],["go","me","n","na","sa","i"],"I'm sorry"],
 [["お","ね","が","い","し","ま","す"],["o","ne","ga","i","shi","ma","su"],"Please — attach it to any request"],
 [["ど","う","ぞ"],["do","u","zo"],"Go ahead / here you go"],
 [["だ","い","じょ","う","ぶ","で","す"],["da","i","jo","u","bu","de","su"],"It's fine / I'm okay"],
 [["け","っ","こ","う","で","す"],["ke","~","ko","u","de","su"],"No thank you"],
 [["し","つ","れ","い","し","ま","す"],["shi","tsu","re","i","shi","ma","su"],"Excuse me — entering or leaving a room"],
 [["お","つ","か","れ","さ","ま","で","す"],["o","tsu","ka","re","sa","ma","de","su"],"Thanks for your work — the all-purpose office greeting"]
]],
["Yes, no, say that again","へんじ",[
 [["は","い"],["ha","i"],"Yes"],
 [["い","い","え"],["i","i","e"],"No"],
 [["わ","か","り","ま","し","た"],["wa","ka","ri","ma","shi","ta"],"Understood / got it"],
 [["わ","か","り","ま","せ","ん"],["wa","ka","ri","ma","se","n"],"I don't understand"],
 [["し","り","ま","せ","ん"],["shi","ri","ma","se","n"],"I don't know"],
 [["に","ほ","ん","ご","が","す","こ","し","わ","か","り","ま","す"],["ni","ho","n","go","ga","su","ko","shi","wa","ka","ri","ma","su"],"I understand a little Japanese"],
 [["え","い","ご","を","は","な","せ","ま","す","か"],["e","i","go","*o","ha","na","se","ma","su","ka"],"Do you speak English?"],
 [["も","う","い","ち","ど","お","ね","が","い","し","ま","す"],["mo","u","i","chi","do","o","ne","ga","i","shi","ma","su"],"One more time, please"],
 [["ゆ","っ","く","り","お","ね","が","い","し","ま","す"],["yu","~","ku","ri","o","ne","ga","i","shi","ma","su"],"Slowly, please"],
 [["こ","れ","で","い","い","で","す","か"],["ko","re","de","i","i","de","su","ka"],"Is this okay?"],
 [["な","ん","と","い","い","ま","す","か"],["na","n","to","i","i","ma","su","ka"],"How do you say it?"]
]],
["Introducing yourself","じこしょうかい",[
 [["わ","た","し","は","ク","イ","ン","シ","ー","で","す"],["wa","ta","shi","*wa","ku","i","n","shi","~","de","su"],"I'm Quincy — your name in katakana"],
 [["カ","ナ","ダ","か","ら","き","ま","し","た"],["ka","na","da","ka","ra","ki","ma","shi","ta"],"I'm from Canada"],
 [["エ","ン","ジ","ニ","ア","で","す"],["e","n","ji","ni","a","de","su"],"I'm an engineer"],
 [["に","ほ","ん","ご","を","べ","ん","きょ","う","し","て","い","ま","す"],["ni","ho","n","go","*o","be","n","kyo","u","shi","te","i","ma","su"],"I'm studying Japanese"],
 [["お","な","ま","え","は","な","ん","で","す","か"],["o","na","ma","e","*wa","na","n","de","su","ka"],"What's your name?"],
 [["し","ご","と","は","な","ん","で","す","か"],["shi","go","to","*wa","na","n","de","su","ka"],"What do you do for work?"],
 [["と","う","きょ","う","に","す","ん","で","い","ま","す"],["to","u","kyo","u","ni","su","n","de","i","ma","su"],"I live in Tokyo"],
 [["しゅ","み","は","な","ん","で","す","か"],["shu","mi","*wa","na","n","de","su","ka"],"What do you do for fun?"]
]],
["Shops and food","かいもの",[
 [["こ","れ","を","く","だ","さ","い"],["ko","re","*o","ku","da","sa","i"],"This one, please — point and say it"],
 [["い","く","ら","で","す","か"],["i","ku","ra","de","su","ka"],"How much is it?"],
 [["メ","ニュ","ー","を","お","ね","が","い","し","ま","す"],["me","nyu","~","*o","o","ne","ga","i","shi","ma","su"],"Menu, please"],
 [["お","す","す","め","は","な","ん","で","す","か"],["o","su","su","me","*wa","na","n","de","su","ka"],"What do you recommend?"],
 [["ひ","と","り","で","す"],["hi","to","ri","de","su"],"Just one — table for one"],
 [["い","た","だ","き","ま","す"],["i","ta","da","ki","ma","su"],"Said just before you eat"],
 [["お","い","し","い","で","す"],["o","i","shi","i","de","su"],"It's delicious"],
 [["ご","ち","そ","う","さ","ま","で","し","た"],["go","chi","so","u","sa","ma","de","shi","ta"],"Said when you finish eating"],
 [["み","ず","を","く","だ","さ","い"],["mi","zu","*o","ku","da","sa","i"],"Water, please"],
 [["に","く","は","た","べ","ま","せ","ん"],["ni","ku","*wa","ta","be","ma","se","n"],"I don't eat meat"],
 [["も","ち","か","え","り","で","す"],["mo","chi","ka","e","ri","de","su"],"Takeaway"],
 [["て","ん","な","い","で","た","べ","ま","す"],["te","n","na","i","de","ta","be","ma","su"],"Eating in"],
 [["お","か","い","け","い","お","ね","が","い","し","ま","す"],["o","ka","i","ke","i","o","ne","ga","i","shi","ma","su"],"The bill, please"],
 [["カ","ー","ド","で","い","い","で","す","か"],["ka","~","do","de","i","i","de","su","ka"],"Is card okay?"],
 [["ふ","く","ろ","は","い","り","ま","せ","ん"],["fu","ku","ro","*wa","i","ri","ma","se","n"],"I don't need a bag"],
 [["す","こ","し","ま","っ","て","く","だ","さ","い"],["su","ko","shi","ma","~","te","ku","da","sa","i"],"One moment, please"],
 [["み","て","い","る","だ","け","で","す"],["mi","te","i","ru","da","ke","de","su"],"Just looking, thanks"],
 [["え","い","ご","の","メ","ニュ","ー","は","あ","り","ま","す","か"],["e","i","go","no","me","nyu","~","*wa","a","ri","ma","su","ka"],"Is there an English menu?"],
 [["め","ん","ぜ","い","で","き","ま","す","か"],["me","n","ze","i","de","ki","ma","su","ka"],"Can I get this tax-free?"],
 [["よ","や","く","し","て","い","ま","せ","ん"],["yo","ya","ku","shi","te","i","ma","se","n"],"I don't have a reservation"]
]],
["Getting around","みち・でんしゃ",[
 [["ト","イ","レ","は","ど","こ","で","す","か"],["to","i","re","*wa","do","ko","de","su","ka"],"Where is the toilet?"],
 [["え","き","は","ど","こ","で","す","か"],["e","ki","*wa","do","ko","de","su","ka"],"Where is the station?"],
 [["こ","こ","は","ど","こ","で","す","か"],["ko","ko","*wa","do","ko","de","su","ka"],"Where am I?"],
 [["こ","れ","は","な","ん","で","す","か"],["ko","re","*wa","na","n","de","su","ka"],"What is this?"],
 [["み","ぎ"],["mi","gi"],"Right"],
 [["ひ","だ","り"],["hi","da","ri"],"Left"],
 [["ま","っ","す","ぐ"],["ma","~","su","gu"],"Straight ahead"],
 [["ち","か","い","で","す","か"],["chi","ka","i","de","su","ka"],"Is it close?"],
 [["あ","る","い","て","い","け","ま","す","か"],["a","ru","i","te","i","ke","ma","su","ka"],"Can I walk there?"],
 [["み","ち","に","ま","よ","い","ま","し","た"],["mi","chi","ni","ma","yo","i","ma","shi","ta"],"I'm lost"],
 [["な","ん","ば","ん","せ","ん","で","す","か"],["na","n","ba","n","se","n","de","su","ka"],"Which platform?"],
 [["つ","ぎ","の","で","ん","しゃ","は","な","ん","じ","で","す","か"],["tsu","gi","no","de","n","sha","*wa","na","n","ji","de","su","ka"],"What time is the next train?"],
 [["き","っ","ぷ","を","か","い","た","い","で","す"],["ki","~","pu","*o","ka","i","ta","i","de","su"],"I'd like to buy a ticket"],
 [["と","う","きょ","う","ま","で","お","ね","が","い","し","ま","す"],["to","u","kyo","u","ma","de","o","ne","ga","i","shi","ma","su"],"To Tokyo, please — say it to a taxi driver"],
 [["しゃ","し","ん","を","と","っ","て","も","い","い","で","す","か"],["sha","shi","n","*o","to","~","te","mo","i","i","de","su","ka"],"May I take a photo?"]
]],
["Numbers and time","かず・じかん",[
 [["い","ち"],["i","chi"],"1"],
 [["に"],["ni"],"2"],
 [["さ","ん"],["sa","n"],"3"],
 [["よ","ん"],["yo","n"],"4"],
 [["ご"],["go"],"5"],
 [["ろ","く"],["ro","ku"],"6"],
 [["な","な"],["na","na"],"7"],
 [["は","ち"],["ha","chi"],"8"],
 [["きゅ","う"],["kyu","u"],"9"],
 [["じゅ","う"],["ju","u"],"10"],
 [["ひゃ","く"],["hya","ku"],"100"],
 [["せ","ん"],["se","n"],"1,000"],
 [["ま","ん"],["ma","n"],"10,000 — Japanese counts in units of man, so ¥30,000 is san-man"],
 [["い","ま","な","ん","じ","で","す","か"],["i","ma","na","n","ji","de","su","ka"],"What time is it?"],
 [["きょ","う"],["kyo","u"],"Today"],
 [["あ","し","た"],["a","shi","ta"],"Tomorrow"],
 [["き","の","う"],["ki","no","u"],"Yesterday"]
]],
["Renting and daily life","せいかつ",[
 [["よ","や","く","を","し","た","い","で","す"],["yo","ya","ku","*o","shi","ta","i","de","su"],"I'd like to make a booking"],
 [["イ","ン","タ","ー","ネ","ッ","ト","は","あ","り","ま","す","か"],["i","n","ta","~","ne","~","to","*wa","a","ri","ma","su","ka"],"Is there internet?"],
 [["げ","ん","き","ん","だ","け","で","す","か"],["ge","n","ki","n","da","ke","de","su","ka"],"Cash only?"],
 [["は","ん","こ","が","ひ","つ","よ","う","で","す","か"],["ha","n","ko","ga","hi","tsu","yo","u","de","su","ka"],"Do I need a personal seal?"],
 [["な","ま","え","を","か","い","て","く","だ","さ","い"],["na","ma","e","*o","ka","i","te","ku","da","sa","i"],"Please write your name"],
 [["ご","み","の","ひ","は","い","つ","で","す","か"],["go","mi","no","hi","*wa","i","tsu","de","su","ka"],"Which day is rubbish day? — Japan takes this seriously"],
 [["こ","わ","れ","て","い","ま","す"],["ko","wa","re","te","i","ma","su"],"It's broken"],
 [["しゅ","う","り","を","お","ね","が","い","し","ま","す"],["shu","u","ri","*o","o","ne","ga","i","shi","ma","su"],"Please arrange a repair"],
 [["ペ","ッ","ト","を","か","っ","て","い","ま","す"],["pe","~","to","*o","ka","~","te","i","ma","su"],"I have pets"],
 [["で","ん","き","を","つ","け","て","く","だ","さ","い"],["de","n","ki","*o","tsu","ke","te","ku","da","sa","i"],"Please turn on the light"]
]],
["If something goes wrong","きんきゅう",[
 [["た","す","け","て"],["ta","su","ke","te"],"Help!"],
 [["びょ","う","い","ん","は","ど","こ","で","す","か"],["byo","u","i","n","*wa","do","ko","de","su","ka"],"Where is the hospital?"],
 [["け","い","さ","つ","を","よ","ん","で","く","だ","さ","い"],["ke","i","sa","tsu","*o","yo","n","de","ku","da","sa","i"],"Please call the police"],
 [["きゅ","う","きゅ","う","しゃ","を","よ","ん","で","く","だ","さ","い"],["kyu","u","kyu","u","sha","*o","yo","n","de","ku","da","sa","i"],"Please call an ambulance"],
 [["さ","い","ふ","を","な","く","し","ま","し","た"],["sa","i","fu","*o","na","ku","shi","ma","shi","ta"],"I lost my wallet"],
 [["パ","ス","ポ","ー","ト","を","な","く","し","ま","し","た"],["pa","su","po","~","to","*o","na","ku","shi","ma","shi","ta"],"I lost my passport"],
 [["き","ぶ","ん","が","わ","る","い","で","す"],["ki","bu","n","ga","wa","ru","i","de","su"],"I don't feel well"],
 [["ア","レ","ル","ギ","ー","が","あ","り","ま","す"],["a","re","ru","gi","~","ga","a","ri","ma","su"],"I have an allergy"],
 [["で","ん","わ","を","か","し","て","く","だ","さ","い"],["de","n","wa","*o","ka","shi","te","ku","da","sa","i"],"Please lend me a phone"],
 [["あ","た","ま","が","い","た","い","で","す"],["a","ta","ma","ga","i","ta","i","de","su"],"My head hurts"],
 [["お","な","か","が","い","た","い","で","す"],["o","na","ka","ga","i","ta","i","de","su"],"My stomach hurts"],
 [["ね","つ","が","あ","り","ま","す"],["ne","tsu","ga","a","ri","ma","su"],"I have a fever"]
]],
["Reacting like a human","きもち",[
 [["す","ご","い"],["su","go","i"],"Wow / amazing"],
 [["か","わ","い","い"],["ka","wa","i","i"],"Cute"],
 [["た","の","し","い","で","す"],["ta","no","shi","i","de","su"],"This is fun"],
 [["う","れ","し","い","で","す"],["u","re","shi","i","de","su"],"I'm happy"],
 [["つ","か","れ","ま","し","た"],["tsu","ka","re","ma","shi","ta"],"I'm worn out"],
 [["あ","つ","い","で","す","ね"],["a","tsu","i","de","su","ne"],"Hot today, isn't it — the national small talk"],
 [["さ","む","い","で","す","ね"],["sa","mu","i","de","su","ne"],"Cold, isn't it"],
 [["ほ","ん","と","う","で","す","か"],["ho","n","to","u","de","su","ka"],"Really?"],
 [["な","る","ほ","ど"],["na","ru","ho","do"],"Ah, I see — that makes sense"],
 [["だ","い","す","き","で","す"],["da","i","su","ki","de","su"],"I love it"]
]],
["Katakana you already know","カタカナ",[
 [["コ","ー","ヒ","ー"],["ko","~","hi","~"],"coffee — kōhī"],
 [["ビ","ー","ル"],["bi","~","ru"],"beer — bīru"],
 [["ト","イ","レ"],["to","i","re"],"toilet"],
 [["コ","ン","ビ","ニ"],["ko","n","bi","ni"],"convenience store"],
 [["ス","ー","パ","ー"],["su","~","pa","~"],"supermarket"],
 [["レ","ス","ト","ラ","ン"],["re","su","to","ra","n"],"restaurant"],
 [["ホ","テ","ル"],["ho","te","ru"],"hotel"],
 [["タ","ク","シ","ー"],["ta","ku","shi","~"],"taxi"],
 [["バ","ス"],["ba","su"],"bus"],
 [["エ","レ","ベ","ー","タ","ー"],["e","re","be","~","ta","~"],"elevator"],
 [["カ","ー","ド"],["ka","~","do"],"card"],
 [["パ","ス","ポ","ー","ト"],["pa","su","po","~","to"],"passport"],
 [["チェ","ッ","ク","イ","ン"],["che","~","ku","i","n"],"check-in"],
 [["イ","ン","タ","ー","ネ","ッ","ト"],["i","n","ta","~","ne","~","to"],"internet"],
 [["ワ","イ","ファ","イ"],["wa","i","fa","i"],"Wi-Fi"],
 [["パ","ソ","コ","ン"],["pa","so","ko","n"],"computer — from \u201cpersonal computer\u201d"],
 [["ス","マ","ホ"],["su","ma","ho"],"smartphone — clipped from sumātofon"],
 [["サ","ー","バ","ー"],["sa","~","ba","~"],"server"],
 [["ア","プ","リ"],["a","pu","ri"],"app"],
 [["メ","ー","ル"],["me","~","ru"],"email"],
 [["エ","ン","ジ","ニ","ア"],["e","n","ji","ni","a"],"engineer"],
 [["カ","ナ","ダ","じ","ん"],["ka","na","da","ji","n"],"Canadian — kanji-era word plus katakana country"]
]],
["Reading practice","よみもの",[
 [["コ","ー","ヒ","ー","を","く","だ","さ","い"],["ko","~","hi","~","*o","ku","da","sa","i"],"Coffee, please — katakana and a particle in one breath"],
 [["え","き","は","ち","か","い","で","す","か"],["e","ki","*wa","chi","ka","i","de","su","ka"],"Is the station close?"],
 [["こ","れ","は","い","く","ら","で","す","か"],["ko","re","*wa","i","ku","ra","de","su","ka"],"How much is this?"],
 [["ト","イ","レ","は","ど","こ","に","あ","り","ま","す","か"],["to","i","re","*wa","do","ko","ni","a","ri","ma","su","ka"],"Where is the toilet? — the ありますか pattern"],
 [["に","ほ","ん","ご","は","た","の","し","い","で","す"],["ni","ho","n","go","*wa","ta","no","shi","i","de","su"],"Japanese is fun"],
 [["あ","し","た","も","き","ま","す","ね"],["a","shi","ta","mo","ki","ma","su","ne"],"I'll come again tomorrow, okay?"]
]],
["Question words","しつもん",[
 [["な","に"],["na","ni"],"What"],
 [["ど","こ"],["do","ko"],"Where"],
 [["い","つ"],["i","tsu"],"When"],
 [["だ","れ"],["da","re"],"Who"],
 [["ど","れ"],["do","re"],"Which one — of three or more"],
 [["ど","っ","ち"],["do","~","chi"],"Which — of two, casual"],
 [["ど","う","や","っ","て"],["do","u","ya","~","te"],"How — by what means"],
 [["ど","う","し","て"],["do","u","shi","te"],"Why"],
 [["い","く","つ"],["i","ku","tsu"],"How many — also how old"]
]],
["Phrases you'll hear","みせで",[
 [["い","ら","っ","しゃ","い","ま","せ"],["i","ra","~","sha","i","ma","se"],"Welcome! — shouted as you enter any shop"],
 [["あ","た","た","め","ま","す","か"],["a","ta","ta","me","ma","su","ka"],"Shall I heat it up? — the konbini bento question"],
 [["お","は","し","は","い","り","ま","す","か"],["o","ha","shi","*wa","i","ri","ma","su","ka"],"Do you need chopsticks?"],
 [["ふ","く","ろ","に","い","れ","ま","す","か"],["fu","ku","ro","ni","i","re","ma","su","ka"],"Shall I put it in a bag?"],
 [["ポ","イ","ン","ト","カ","ー","ド","は","お","も","ち","で","す","か"],["po","i","n","to","ka","~","do","*wa","o","mo","chi","de","su","ka"],"Do you have a point card?"],
 [["こ","ち","ら","で","お","め","し","あ","が","り","で","す","か"],["ko","chi","ra","de","o","me","shi","a","ga","ri","de","su","ka"],"Eating here? — for here or to go"],
 [["い","じょ","う","で","よ","ろ","し","い","で","す","か"],["i","jo","u","de","yo","ro","shi","i","de","su","ka"],"Will that be all?"],
 [["しょ","う","しょ","う","お","ま","ち","く","だ","さ","い"],["sho","u","sho","u","o","ma","chi","ku","da","sa","i"],"One moment, please — the keigo version staff use"],
 [["お","ま","た","せ","し","ま","し","た"],["o","ma","ta","se","shi","ma","shi","ta"],"Sorry to keep you waiting"]
]],
["Counting things","かぞえかた",[
 [["ひ","と","つ"],["hi","to","tsu"],"One — of anything"],
 [["ふ","た","つ"],["fu","ta","tsu"],"Two"],
 [["み","っ","つ"],["mi","~","tsu"],"Three"],
 [["よ","っ","つ"],["yo","~","tsu"],"Four"],
 [["い","つ","つ"],["i","tsu","tsu"],"Five"],
 [["む","っ","つ"],["mu","~","tsu"],"Six"],
 [["な","な","つ"],["na","na","tsu"],"Seven"],
 [["や","っ","つ"],["ya","~","tsu"],"Eight"],
 [["こ","こ","の","つ"],["ko","ko","no","tsu"],"Nine"],
 [["と","お"],["to","o"],"Ten — after ten, switch to plain numbers"],
 [["ふ","た","つ","く","だ","さ","い"],["fu","ta","tsu","ku","da","sa","i"],"Two of those, please — the counter in action"]
]],
["Days of the week","ようび",[
 [["げ","つ","よ","う","び"],["ge","tsu","yo","u","bi"],"Monday — moon day"],
 [["か","よ","う","び"],["ka","yo","u","bi"],"Tuesday — fire day"],
 [["す","い","よ","う","び"],["su","i","yo","u","bi"],"Wednesday — water day"],
 [["も","く","よ","う","び"],["mo","ku","yo","u","bi"],"Thursday — wood day"],
 [["き","ん","よ","う","び"],["ki","n","yo","u","bi"],"Friday — gold day"],
 [["ど","よ","う","び"],["do","yo","u","bi"],"Saturday — earth day"],
 [["に","ち","よ","う","び"],["ni","chi","yo","u","bi"],"Sunday — sun day"],
 [["きょ","う","は","な","ん","よ","う","び","で","す","か"],["kyo","u","*wa","na","n","yo","u","bi","de","su","ka"],"What day is it today?"],
 [["しゅ","う","ま","つ"],["shu","u","ma","tsu"],"Weekend"]
]],
["Essential verbs","どうし",[
 [["い","き","ま","す"],["i","ki","ma","su"],"To go"],
 [["き","ま","す"],["ki","ma","su"],"To come"],
 [["か","え","り","ま","す"],["ka","e","ri","ma","su"],"To go home"],
 [["た","べ","ま","す"],["ta","be","ma","su"],"To eat"],
 [["の","み","ま","す"],["no","mi","ma","su"],"To drink"],
 [["み","ま","す"],["mi","ma","su"],"To see, to watch"],
 [["き","き","ま","す"],["ki","ki","ma","su"],"To listen — also to ask"],
 [["は","な","し","ま","す"],["ha","na","shi","ma","su"],"To speak"],
 [["か","い","ま","す"],["ka","i","ma","su"],"To buy"],
 [["わ","か","り","ま","す"],["wa","ka","ri","ma","su"],"To understand"],
 [["あ","り","ま","す"],["a","ri","ma","su"],"There is — things"],
 [["い","ま","す"],["i","ma","su"],"There is — people and animals"],
 [["し","ま","す"],["shi","ma","su"],"To do"],
 [["ね","ま","す"],["ne","ma","su"],"To sleep"]
]],
["Essential adjectives","けいようし",[
 [["お","お","き","い"],["o","o","ki","i"],"Big"],
 [["ち","い","さ","い"],["chi","i","sa","i"],"Small"],
 [["た","か","い"],["ta","ka","i"],"Expensive — also tall"],
 [["や","す","い"],["ya","su","i"],"Cheap"],
 [["い","い"],["i","i"],"Good"],
 [["わ","る","い"],["wa","ru","i"],"Bad"],
 [["は","や","い"],["ha","ya","i"],"Fast — also early"],
 [["お","そ","い"],["o","so","i"],"Slow — also late"],
 [["あ","た","ら","し","い"],["a","ta","ra","shi","i"],"New"],
 [["ふ","る","い"],["fu","ru","i"],"Old — for things, not people"],
 [["と","お","い"],["to","o","i"],"Far"],
 [["む","ず","か","し","い"],["mu","zu","ka","shi","i"],"Difficult"],
 [["か","ん","た","ん"],["ka","n","ta","n"],"Easy, simple"]
]],
["Basic grammar","ぶんぽう",[
 [["わ","た","し","は","が","く","せ","い","で","す"],["wa","ta","shi","*wa","ga","ku","se","i","de","su"],"I am a student — XはYです, the master sentence"],
 [["こ","れ","は","ほ","ん","じゃ","な","い","で","す"],["ko","re","*wa","ho","n","ja","na","i","de","su"],"This isn't a book — じゃないです makes です negative"],
 [["き","の","う","は","あ","め","で","し","た"],["ki","no","u","*wa","a","me","de","shi","ta"],"Yesterday was rainy — でした is past です"],
 [["み","ず","を","の","み","ま","す"],["mi","zu","*o","no","mi","ma","su"],"I drink water — を marks what the verb acts on"],
 [["と","う","きょ","う","に","い","き","ま","す"],["to","u","kyo","u","ni","i","ki","ma","su"],"I go to Tokyo — に marks the destination"],
 [["で","ん","しゃ","で","い","き","ま","す"],["de","n","sha","de","i","ki","ma","su"],"I go by train — で marks the means"],
 [["レ","ス","ト","ラ","ン","で","た","べ","ま","す"],["re","su","to","ra","n","de","ta","be","ma","su"],"I eat at a restaurant — で also marks where the action happens"],
 [["こ","れ","は","わ","た","し","の","か","ば","ん","で","す"],["ko","re","*wa","wa","ta","shi","no","ka","ba","n","de","su"],"This is my bag — の makes possession"],
 [["わ","た","し","も","い","き","ま","す"],["wa","ta","shi","mo","i","ki","ma","su"],"I'm going too — も replaces は to say 'also'"],
 [["こ","れ","は","だ","れ","の","で","す","か"],["ko","re","*wa","da","re","no","de","su","ka"],"Whose is this? — か turns any statement into a question"],
 [["す","し","を","た","べ","ま","し","た"],["su","shi","*o","ta","be","ma","shi","ta"],"I ate sushi — ました is past tense"],
 [["に","く","を","た","べ","ま","せ","ん"],["ni","ku","*o","ta","be","ma","se","n"],"I don't eat meat — ません is the negative"],
 [["き","の","う","べ","ん","きょ","う","し","ま","せ","ん","で","し","た"],["ki","no","u","be","n","kyo","u","shi","ma","se","n","de","shi","ta"],"I didn't study yesterday — ませんでした is past negative"],
 [["み","ず","が","あ","り","ま","す"],["mi","zu","ga","a","ri","ma","su"],"There is water — あります for things, が spotlights what exists"],
 [["ね","こ","が","い","ま","す"],["ne","ko","ga","i","ma","su"],"There is a cat — います for living things"],
 [["に","ほ","ん","に","い","き","た","い","で","す"],["ni","ho","n","ni","i","ki","ta","i","de","su"],"I want to go to Japan — 〜たいです expresses wanting"],
 [["ま","ど","を","あ","け","て","も","い","い","で","す","か"],["ma","do","*o","a","ke","te","mo","i","i","de","su","ka"],"May I open the window? — 〜てもいいですか asks permission"],
 [["しゃ","し","ん","を","と","ら","な","い","で","く","だ","さ","い"],["sha","shi","n","*o","to","ra","na","i","de","ku","da","sa","i"],"Please don't take photos — 〜ないでください forbids politely"],
 [["こ","の","ラ","ー","メ","ン","は","お","い","し","い","で","す"],["ko","no","ra","~","me","n","*wa","o","i","shi","i","de","su"],"This ramen is delicious — い-adjectives sit straight before です"],
 [["た","か","く","な","い","で","す"],["ta","ka","ku","na","i","de","su"],"It's not expensive — い-adjectives flip to 〜くない in the negative"]
]]
];

/* kanji signs: [kanji, furigana, romaji, meaning, where you'll see it] */
const KANJI=[
 ["出口","でぐち","deguchi","exit","every station and shop"],
 ["入口","いりぐち","iriguchi","entrance","doors, gates"],
 ["駅","えき","eki","station","maps, signs"],
 ["円","えん","en","yen","every price tag"],
 ["改札","かいさつ","kaisatsu","ticket gate","stations"],
 ["電車","でんしゃ","densha","train","platforms, apps"],
 ["銀行","ぎんこう","ginkō","bank","street signs"],
 ["病院","びょういん","byōin","hospital","maps, buildings"],
 ["薬局","やっきょく","yakkyoku","pharmacy","green cross signs"],
 ["押","おす","osu","push","door handles"],
 ["引","ひく","hiku","pull","door handles"],
 ["開","ひらく","hiraku","open","elevator buttons"],
 ["閉","しめる","shimeru","close","elevator buttons"],
 ["営業中","えいぎょうちゅう","eigyōchū","open for business","shop doors"],
 ["準備中","じゅんびちゅう","junbichū","closed — preparing","shop doors"],
 ["男","おとこ","otoko","men","toilets, baths"],
 ["女","おんな","onna","women","toilets, baths"],
 ["水","みず","mizu","water","taps, menus"],
 ["お湯","おゆ","oyu","hot water","taps, baths"],
 ["大","だい","dai","large","sizes, flush buttons"],
 ["小","しょう","shō","small","sizes, flush buttons"],
 ["無料","むりょう","muryō","free of charge","signs, apps"],
 ["有料","ゆうりょう","yūryō","paid / fee applies","parking, toilets"],
 ["割引","わりびき","waribiki","discount","supermarket stickers"],
 ["税込","ぜいこみ","zeikomi","tax included","price tags"],
 ["受付","うけつけ","uketsuke","reception","offices, clinics"],
 ["非常口","ひじょうぐち","hijōguchi","emergency exit","green running-man sign"],
 ["注意","ちゅうい","chūi","caution","yellow signs"],
 ["危険","きけん","kiken","danger","red signs"],
 ["止まれ","とまれ","tomare","stop","road markings"]
];



/* Mnemonics derived from the shared KANA_INFO table (js/kana-data.js) */
const MNEM = Object.fromEntries(Object.entries(KANA_INFO).map(([r, v]) => [r, [v.mh, v.mk]]));
