// Builds js/pitch-data.js — the pitch accent of the trainer's words — from the
// Kanjium accent list (https://github.com/mifunetoshiro/kanjium, file
// data/source_files/raw/accents.txt, CC BY-SA 4.0; the accents are Uros O.'s).
// The 3 MB source stays out of the repo; only the entries the trainer uses
// are kept.
//   node tools/gen_pitch.mjs path/to/accents.txt
//
// A card is matched on identity, never on sound alone, because homophones
// carry different accents: a kanji card needs the exact (word, reading) pair;
// a phrase needs an entry whose headword is the phrase itself, or — failing
// that — a reading that every entry sharing it gives the same accent for.
// Whole sentences are not in a word dictionary and are left out.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = process.argv[2];
if (!src) { console.error('usage: node tools/gen_pitch.mjs path/to/accents.txt'); process.exit(1); }
const { loadApp } = await import(pathToFileURL(join(root, 'tools/load-app.mjs')).href);
const { CARDS } = loadApp();

const hira = (s) => s.replace(/[ァ-ヶ]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0x60));
const isKana = (s) => /^[぀-ヿー]+$/.test(s);

/* Entries that share a reading with the phrase but are a different word. */
const DENY = {
  'p:たすけて': '助けて is a verb form; the entry matched is 助け手',
};

const byHead = new Map(), byRead = new Map(), byPair = new Map();
for (const line of readFileSync(src, 'utf8').split('\n')) {
  const [w, r0, a] = line.split('\t');
  if (!w || !a) continue;
  const acc = [...new Set(a.trim().split(',').map(Number))];
  if (acc.some((n) => !Number.isInteger(n) || n < 0)) continue;
  const r = hira(r0 || (isKana(w) ? w : ''));
  if (!r) continue;
  (byHead.get(w) || byHead.set(w, []).get(w)).push({ r, acc });
  (byRead.get(r) || byRead.set(r, []).get(r)).push({ w, acc });
  byPair.set(w + '|' + r, acc);
}
const sameAcc = (list) => new Set(list.map((x) => x.acc.join(','))).size === 1;

const out = {}, report = [];
for (const c of CARDS) {
  if (c.custom || DENY[c.id]) continue;
  let acc = null, how = '';
  if (c.type === 'kanji') {
    acc = byPair.get(c.kanji + '|' + hira(c.furi)); how = 'word+reading';
  } else if (c.type === 'phrase') {
    const text = c.kana.join(''), r = hira(text);
    const head = (byHead.get(text) || []).filter((e) => e.r === r);
    /* loanwords (katakana) have no homophones to confuse; a hiragana word is only
       trusted when every entry sharing its reading agrees, as the list itself
       sometimes disagrees between 誰 and だれ */
    const loan = /^[ァ-ヶー]+$/.test(text);
    if (head.length && sameAcc(head) && (loan || sameAcc(byRead.get(r)))) { acc = head[0].acc; how = 'headword'; }
    else if (!head.length) {
      const list = byRead.get(r);
      if (list && sameAcc(list)) { acc = list[0].acc; how = 'unique reading'; }
    }
  }
  if (acc) { out[c.id] = acc; report.push(`${how.padEnd(14)} ${c.id} ${acc.join(',')}`); }
}

const body = Object.entries(out).map(([id, a]) => `  ${JSON.stringify(id)}: ${JSON.stringify(a)}`).join(',\n');
writeFileSync(join(root, 'js/pitch-data.js'), `/* Pitch accent of the trainer's words: card id -> accent nucleus (the mora
   after which the pitch falls; 0 = flat, no fall). More than one number means
   the dictionary lists several; the first is the main one.

   Generated by tools/gen_pitch.mjs — do not edit by hand.
   Source: Kanjium (https://github.com/mifunetoshiro/kanjium), accents.txt,
   whose pitch accent data comes from Uros O.'s free database. Licensed under
   Creative Commons Attribution-ShareAlike 4.0 International
   (https://creativecommons.org/licenses/by-sa/4.0/); this file is a
   modified extract and carries the same licence.                           */
const PITCH = {
${body}
};
`);
console.log(report.join('\n'));
console.log(`\n${Object.keys(out).length} of ${CARDS.filter((c) => !c.custom && (c.type === 'phrase' || c.type === 'kanji')).length} phrase and kanji cards`);
